<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitamcampus</title>

</head>
<body>
<header>
    <h1>Fitamcampus</h1>

</header>
<main>
    <div>
        <h1>Fitamcampus</h1>
        <div class="button-container">
            <button onclick="window.location.href='/register'">Registrierung</button>
            <button onclick="window.location.href='/login'">Login</button>
        </div>
    </div>
</main>
</body>
</html>
